import React, { useEffect, useRef, useState } from 'react';
import { X, Eye, EyeOff, Mail, Lock, User, Shield, ArrowRight } from 'lucide-react';

const LoginPanel = ({ isOpen, onClose, onLogin, title, subtitle, type, registerAction }) => {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [isLoading, setIsLoading] = useState(false); const [error, setError] = useState(''); const panelRef = useRef(null);
  useEffect(() => { if (isOpen) { setError(''); setTimeout(() => panelRef.current?.querySelector('input')?.focus(), 100); } }, [isOpen]);
  useEffect(() => { const close = (event) => event.key === 'Escape' && onClose(); document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [onClose]);
  if (!isOpen) return null;
  const citizen = type === 'citizen'; const demoEmail = citizen ? 'citizen@nagarsetu.in' : 'admin@nagarsetu.in'; const demoPassword = citizen ? 'citizen123' : 'admin123';
  const handleSubmit = async (event) => { event.preventDefault(); setError(''); setIsLoading(true); await new Promise((resolve) => setTimeout(resolve, 650)); if (email === demoEmail && password === demoPassword) { onLogin({ name: citizen ? 'Citizen User' : 'Administrator', email, role: citizen ? 'citizen' : 'admin' }); onClose(); } else setError('Use the demo credentials shown below.'); setIsLoading(false); };
  return <div className="panel-container auth-overlay" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="auth-card" ref={panelRef} aria-modal="true" role="dialog" aria-label={title}><div className="auth-art"><div className="auth-art-mark">{citizen ? <User size={24}/> : <Shield size={24}/>}</div><p>{citizen ? 'Citizen portal' : 'Department portal'}</p><h2>{citizen ? 'Better neighbourhoods start with a clear report.' : 'Turn every issue into a visible resolution.'}</h2><span>NagarSetu connects people, departments, and practical civic action.</span></div><div className="auth-form"><button className="auth-close" onClick={onClose} aria-label="Close"><X size={20}/></button><p className="auth-kicker">Welcome back</p><h1>{title}</h1><p className="auth-subtitle">{subtitle}</p><form onSubmit={handleSubmit}>{error && <p className="auth-error">{error}</p>}<label>Email address<span className="auth-input"><Mail size={17}/><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" required /></span></label><label>Password<span className="auth-input"><Lock size={17}/><input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" required /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label="Show or hide password">{showPassword ? <EyeOff size={17}/> : <Eye size={17}/>}</button></span></label><button className="auth-submit" type="submit" disabled={isLoading}>{isLoading ? 'Signing in…' : <>Sign in <ArrowRight size={17}/></>}</button></form>{citizen && registerAction && <button className="auth-register" onClick={registerAction}>New to NagarSetu? <b>Create an account</b></button>}<div className="auth-demo"><strong>Demo access</strong><span>{demoEmail}</span><span>Password: {demoPassword}</span></div></div></section></div>;
};

export default LoginPanel;
